### ISSUE TITLE
[Typescript] FormSubscription interface should have optinal keys

### ISSUE THREAD

**Issue by thupi** [ForbesLindesay/define-form#5]
Hi, 

As i was testing the performance optimizing features of react-final-form using react-define-form i found it a bit cumbersom to defined all of the options in the subscription props in order to optimize the rendering.

I would suggest that the FormSubscription interface either had optinal keys or maybe used Partial<T> in order to make it easier to use :-)

**Comment by ForbesLindesay** [comment]
I'm happy to accept a pull request to add the `?` before each `:` in https://github.com/ForbesLindesay/define-form/blob/master/packages/define-form/src/index.d.ts#L14-L31

**Comment by thupi** [comment]
Alright :-) 

I am a bit new to the open source community and so on :-) 

Please let me know if i didnt do it the right way :-)
